workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2 # Updated to M2 for 2026 context
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          xcodegen generate
      - name: Build IPA
        script: |
          xcodebuild -project XYIdactyl.xcodeproj \
            -scheme XYIdactyl \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/XYIdactyl.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
          # Payload creation for Sideloading
          mkdir -p Payload
          mv $CM_BUILD_DIR/XYIdactyl.xcarchive/Products/Applications/XYIdactyl.app Payload/
          zip -r XYIdactyl.ipa Payload
    artifacts:
      - "*.ipa"
      - "*.xcarchive"
