workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          xcodegen generate
      - name: Build IPA
        script: |
          set -e # Fail script if build fails
          
          # Clean build directory
          rm -rf build
          mkdir build
          
          # Archive using relative path 'build/' to avoid env var confusion
          xcodebuild -project XYIdactyl.xcodeproj \
            -scheme XYIdactyl \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/XYIdactyl.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
          # Verify existence
          if [ ! -d "build/XYIdactyl.xcarchive/Products/Applications/XYIdactyl.app" ]; then
            echo "Error: App bundle not found in archive!"
            ls -R build/
            exit 1
          fi
            
          # Payload creation
          rm -rf Payload
          mkdir -p Payload
          cp -R build/XYIdactyl.xcarchive/Products/Applications/XYIdactyl.app Payload/
          
          # Zip
          zip -r XYIdactyl.ipa Payload
    artifacts:
      - "*.ipa"
      - "build/*.xcarchive"
