name: XYIdactyl
options:
  bundleIdPrefix: com.xyidactyl
targets:
  XYIdactyl:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources: 
      - Sources
    resources:
      - Sources/Resources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.xyidactyl.app
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
        SWIFT_VERSION: 5.10
