
import Foundation

struct AgentEggDefinition {
    static let name = "XYIDactyl Agent"
    static let description = "Self-hosted monitoring, alerting, and automation agent for the XYIDactyl iOS app. Runs as a background worker with zero inbound networking."
    static let dockerImage = "ghcr.io/xyidactyl/agent:latest"
    static let startup = "/app/entrypoint.sh"
    
    static let script = """
    #!/bin/ash
    # Installation handled by Docker image
    echo 'XYIDactyl Agent installed'
    """
    
    static let config: [String: Any] = [
        "files": [:],
        "startup": ["done": "Agent is running"],
        "logs": [:],
        "stop": "^^C"
    ]
    
    static let variables: [[String: Any]] = [
        [
            "name": "Agent UUID",
            "description": "Unique identifier for this agent instance. Generated by the iOS app during deployment.",
            "env_variable": "AGENT_UUID",
            "default_value": "",
            "user_viewable": true,
            "user_editable": false,
            "rules": "required|string|max:64"
        ],
        [
            "name": "Agent Secret",
            "description": "Shared secret for encryption. Generated by the iOS app during deployment.",
            "env_variable": "AGENT_SECRET",
            "default_value": "",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|string|min:32"
        ],
        [
            "name": "Panel URL",
            "description": "Full URL of the Pterodactyl panel (e.g., https://panel.example.com).",
            "env_variable": "PANEL_URL",
            "default_value": "",
            "user_viewable": true,
            "user_editable": false,
            "rules": "required|string|max:255"
        ],
        [
            "name": "Panel API Key",
            "description": "Admin API key for the Pterodactyl panel.",
            "env_variable": "PANEL_API_KEY",
            "default_value": "",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|string"
        ],
        [
            "name": "Sampling Interval",
            "description": "How often to poll server resources (in seconds). Default: 30.",
            "env_variable": "SAMPLING_INTERVAL",
            "default_value": "30",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|integer|between:5,300"
        ],
        [
            "name": "Retention Days",
            "description": "How many days to keep monitoring data. Maximum: 30.",
            "env_variable": "RETENTION_DAYS",
            "default_value": "30",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|integer|between:1,30"
        ],
        [
            "name": "Push Provider",
            "description": "Push notification provider: 'dev' (logs to console) or 'apns' (Apple Push).",
            "env_variable": "PUSH_PROVIDER",
            "default_value": "dev",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|in:dev,apns"
        ],
        [
            "name": "APNs Key Base64",
            "description": "Base64-encoded .p8 key file for Apple Push Notifications. Required when PUSH_PROVIDER=apns.",
            "env_variable": "APNS_KEY_BASE64",
            "default_value": "",
            "user_viewable": false,
            "user_editable": true,
            "rules": "nullable|string"
        ],
        [
            "name": "APNs Key ID",
            "description": "Key ID from Apple Developer account. Required when PUSH_PROVIDER=apns.",
            "env_variable": "APNS_KEY_ID",
            "default_value": "",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|string|max:20"
        ],
        [
            "name": "APNs Team ID",
            "description": "Team ID from Apple Developer account. Required when PUSH_PROVIDER=apns.",
            "env_variable": "APNS_TEAM_ID",
            "default_value": "",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|string|max:20"
        ],
        [
            "name": "APNs Bundle ID",
            "description": "iOS app bundle identifier. Required when PUSH_PROVIDER=apns.",
            "env_variable": "APNS_BUNDLE_ID",
            "default_value": "com.xyidactyl.app",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|string|max:255"
        ],
        [
            "name": "Log Level",
            "description": "Logging verbosity: debug, info, warn, error.",
            "env_variable": "LOG_LEVEL",
            "default_value": "info",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|in:debug,info,warn,error"
        ]
    ]
}
